### PR TITLE
 Update GPT-3.5 translated locales using GPT-4o 

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Per discussion in #43, as old translations were translated by GPT-3.5, we should use GPT-4o to improve.

### CODE REVIEW

**Comment by Christopher-Hayes** [comment]
Amazing, thank you!

**Comment by PeterDaveHello** [comment]
@Christopher-Hayes did you mean that new features haven't been processed with i18n in #43? Wonder if I can help, but I'm not sure.

**Comment by Christopher-Hayes** [comment]
@PeterDaveHello some of it was not updating translations for `gpt-4o`, which you converted, thank you. There's also some new UI elements that I haven't hooked up with translation files yet. For example, the "Local LLM Settings" UI is not yet translated. I need to update the frontend to hook it up to new translation file keys. And then those keys need to be localized to each language. So, if you're feeling ambitious and want to help out in the React frontend, you can try adding `t` to components that aren't yet translated. Or you can wait until I do that, and just update the translation files. Up to you, whatever you're interested in working on.

**Comment by PeterDaveHello** [comment]
I'll see what I can do with that.

BTW would more comprehensive or complete locale support look helpful to you? As the content isn't too large, wouldn't be too hard to do so. If you'd like it, do I simply add locale files like `package.nls.vi.json`?

Thanks.

**Comment by PeterDaveHello** [comment]
Let me help open #76 first.

**Comment by Christopher-Hayes** [comment]
> I'll see what I can do with that.
> 
> BTW would more comprehensive or complete locale support look helpful to you? As the content isn't too large, wouldn't be too hard to do so. If you'd like it, do I simply add locale files like `package.nls.vi.json`?
> 
> Some other locales can be added might be:
> 
>     * ar
> 
>     * bg
> 
>     * ca
> 
>     * cs
> 
>     * da
> 
>     * el
> 
>     * fa
> 
>     * fi
> 
>     * he
> 
>     * hi
> 
>     * hr
> 
>     * hu
> 
>     * id
> 
>     * is
> 
>     * lt
> 
>     * lv
> 
>     * ms
> 
>     * no
> 
>     * ro
> 
>     * ru
> 
>     * sk
> 
>     * sl
> 
>     * sr
> 
>     * sv
> 
>     * th
> 
>     * vi
> 
> 
> Thanks.

Sure, we can definitely add new locales. I just want to strike a balance between what languages our users are likely using and a list of languages that is not too difficult to update.

Btw, was just looking around, and https://github.com/lokalise/i18n-ally looks pretty neat. So, maybe one day that tool can help us translate. It seems like a lot of work to add though, so maybe a long-term thing. I only mention it because I'm open to new ideas or tools, if you feel like adding one.

**Comment by PeterDaveHello** [comment]
Cool, I haven't tried i18n-ally yet, could take a look at it.

So if you don't have any preference yet, I'd see what the priorities might be, and send a PR later.

**Comment by Christopher-Hayes** [comment]
@PeterDaveHello I put together a list of which languages we should prioritize here: https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/issues/77

But, if you feel compelled to add a specific language not in that list, by all means add that language.

**Pull request merged**
