### PR TITLE
Fix languages

### PR DESCRIPTION
**Pull request by PeterDaveHello**
I bet you use AI to translate it 😈

### CODE REVIEW

**Comment by Christopher-Hayes** [comment]
You're correct 😂 Thank you again for the PR. Will get this merged later today.

**Comment by PeterDaveHello** [comment]
@Christopher-Hayes would a gpt-4o re-translation for those gpt-3.5(?) translated locales looks good to you? I can help with that.

**Comment by Christopher-Hayes** [comment]
@PeterDaveHello yeah if you can help that, it would be much appreciated. Sorry, I've gotten behind on translating everything.

**Comment by PeterDaveHello** [comment]
No worries, I'll be happy to help.

**Comment by PeterDaveHello** [comment]
#75 sent.

**Pull request merged**
