### PR TITLE
Update zh-CN.json

### PR DESCRIPTION
**Pull request by zzy-life**
Add translation content

### CODE REVIEW

**Comment by zzy-life** [comment]
Implementing automatic internationalization of right-click menu bar by moving i18n files,
Tested in three language environments
Japanese:
image
English:
image
Chinese:
image

**Comment by zzy-life** [comment]
https://github.com/shanalikhan/code-settings-sync
Their libraries are all done this way, and I found that vscode nls didn't work, maybe

**Comment by Christopher-Hayes** [comment]
thank you! I'll get this in the next release.

**Comment by Christopher-Hayes** [comment]
Looks good. Merged.

**Comment by Christopher-Hayes** [comment]
Thank you for the refactor, this has been pushed in release `v3.16.3`.

**Pull request merged**
