### PR TITLE
added support for gtp 3.5 1k context

### PR DESCRIPTION
**Pull request by raphael2692**
I checked model id from openai models api and set it it the package json and Model enum. I made a test and it seems to work fine (the debugger shows that the reqest was made to gpt-3.5-turbo-16k-0613). 

Let me know if I forgot something :)

### CODE REVIEW

**Comment by rambalachandran** [comment]
@Christopher-Hayes please review and merge as this model will be a game changer for many code bases.

**Comment by raphael2692** [comment]
> This seems to modify only `package.json` of English and not of other languages. I'm not sure if that can create issues.

I am reading the localized package json, do you know if these values "chatgpt.gpt3.model.enumItemLabels1" refers to something hardcoded? (I think they not). If not I could just update all json and update the pr...

**Comment by Christopher-Hayes** [comment]
Thank you @raphael2692 and @rambalachandran 

Yeah, the `package.nls.<localization>.json` files include localization for extension settings found in the `package.json`.
ie - in `package.json` inside the `chatgpt.gpt3.model` object, the first item of the `enumItemLabels: []` array corresponds to the `chatgpt.gpt3.model.enumItemLabels1` key in localization files.

It's no problem, I can add those easily enough.

**Comment by Christopher-Hayes** [comment]
Things seem to be working. I won't get to merging/releasing this tonight, but tomorrow I should have time. Feel free to test this branch before it gets released.

Just as an FYI - the `gpt-3.5-turbo-16k` instead of the `gpt-3.5-turbo-16k-0613` model will show up in the model dropdown. I'm also removing the 3.5 0314 model. These models are meant for apps that require a model from OpenAI that never gets updates, it's not needed for this extension. It's probably better for the UX if things are kept simple, and these models are omitted.

**Comment by raphael2692** [comment]
thanks @Christopher-Hayes , can't wait to use it in vscode :-)

**Comment by Christopher-Hayes** [comment]
`v3.17.0` has been released! Thank you again for bringing this to my attention.

**Comment by rambalachandran** [comment]
Awsome. Thank you so much @Christopher-Hayes this is very useful in VSCode

**Pull request merged**
